### ISSUE TITLE
Net::IMAP::NoResponseError in imap.rb

### ISSUE THREAD

**Issue by firedev** [mailman/mailman#107]
Hi,

After a while mailman hanged with the following output:

```
 IMAP receiver enabled (no-reply@thehouseproject.info@imap.gmail.com).
I, [2014-09-18T03:38:09.990508 #21001]  INFO -- : Polling enabled. Checking every 5 seconds.
/home/rails/.rbenv/versions/2.1.1/lib/ruby/2.1.0/net/imap.rb:1156:in `get_tagged_response': System error (Failure) (Net::IMAP::NoResponseError)
        from /home/rails/.rbenv/versions/2.1.1/lib/ruby/2.1.0/net/imap.rb:1210:in `block in send_command'
        from /home/rails/.rbenv/versions/2.1.1/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
        from /home/rails/.rbenv/versions/2.1.1/lib/ruby/2.1.0/net/imap.rb:1192:in `send_command'
        ...
```

I have `rescue IOError` in the loop already, added this one as well. Is this normal behaviour? This is the first time this error was raised.

What are general best practices for deploying mailman so it can run unattened? It either hangs or dies after a while.

**Comment by CUnknown** [comment]
Is this the same issue? I'm running mailman version 0.7.0, which is the most recent version from ruby-gems. I will try github master@93bced2 now...

`/home/christiaan/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/imap.rb:1190:in `get_tagged_response':  Temporary System Error (Net::IMAP::ByeResponseError)
	from /home/christiaan/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/imap.rb:1250:in `block in send_command'
	from /home/christiaan/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
	from /home/christiaan/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/imap.rb:1232:in `send_command'
	from /home/christiaan/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/imap.rb:436:in `login'
	from /home/christiaan/.rvm/gems/ruby-2.3.0/gems/mailman-0.7.0/lib/mailman/receiver/imap.rb:40:in `connect'
	from /home/christiaan/.rvm/gems/ruby-2.3.0/gems/mailman-0.7.0/lib/mailman/application.rb:132:in `block in polling_loop'
	from /home/christiaan/.rvm/gems/ruby-2.3.0/gems/mailman-0.7.0/lib/mailman/application.rb:130:in `loop'
	from /home/christiaan/.rvm/gems/ruby-2.3.0/gems/mailman-0.7.0/lib/mailman/application.rb:130:in `polling_loop'
	from /home/christiaan/.rvm/gems/ruby-2.3.0/gems/mailman-0.7.0/lib/mailman/application.rb:77:in `run'
	from /home/christiaan/.rvm/gems/ruby-2.3.0/gems/mailman-0.7.0/lib/mailman/application.rb:11:in `run'
	from bin/mailman_server:13:in `<main>'`

**Comment by RBIII** [comment]
Was there ever a fix for this? I'm getting a
```
Net::IMAP::NoResponseError:  Please log in via your web browser: https://support.google.com/mail/accounts/answer/78754 (Failure)
```
no matter what server/port/ssl status I try
