### ISSUE TITLE
Occasional "EOFError: end of file reached" exception

### ISSUE THREAD

**Issue by KieranP** [mailman/mailman#74]
For days at a time, mailman works great. Then every so often I get the exception "EOFError: end of file reached" which crashes the mailman server.

Here is the stack trace:

```
/home/user/.rvm/rubies/ruby-1.9.3-p385/lib/ruby/1.9.1/openssl/buffering.rb:174:in `sysread_nonblock'
/home/user/.rvm/rubies/ruby-1.9.3-p385/lib/ruby/1.9.1/openssl/buffering.rb:174:in `read_nonblock'
/home/user/.rvm/rubies/ruby-1.9.3-p385/lib/ruby/1.9.1/net/protocol.rb:141:in `rbuf_fill'
/home/user/.rvm/rubies/ruby-1.9.3-p385/lib/ruby/1.9.1/net/protocol.rb:122:in `readuntil'
/home/user/.rvm/rubies/ruby-1.9.3-p385/lib/ruby/1.9.1/net/protocol.rb:132:in `readline'
/home/user/.rvm/rubies/ruby-1.9.3-p385/lib/ruby/1.9.1/net/pop.rb:996:in `recv_response'
/home/user/.rvm/rubies/ruby-1.9.3-p385/lib/ruby/1.9.1/net/pop.rb:992:in `get_response'
/home/user/.rvm/rubies/ruby-1.9.3-p385/lib/ruby/1.9.1/net/pop.rb:905:in `block in auth'
/home/user/.rvm/rubies/ruby-1.9.3-p385/lib/ruby/1.9.1/net/pop.rb:1012:in `critical'
/home/user/.rvm/rubies/ruby-1.9.3-p385/lib/ruby/1.9.1/net/pop.rb:904:in `auth'
/home/user/.rvm/rubies/ruby-1.9.3-p385/lib/ruby/1.9.1/net/pop.rb:566:in `do_start'
/home/user/.rvm/rubies/ruby-1.9.3-p385/lib/ruby/1.9.1/net/pop.rb:538:in `start'
[GEM_ROOT]/gems/mailman-0.6.0/lib/mailman/receiver/pop3.rb:29:in `connect'
[GEM_ROOT]/gems/mailman-0.6.0/lib/mailman/application.rb:117:in `block in polling_loop'
[GEM_ROOT]/gems/mailman-0.6.0/lib/mailman/application.rb:115:in `loop'
[GEM_ROOT]/gems/mailman-0.6.0/lib/mailman/application.rb:115:in `polling_loop'
[GEM_ROOT]/gems/mailman-0.6.0/lib/mailman/application.rb:75:in `run'
[GEM_ROOT]/gems/mailman-0.6.0/lib/mailman/application.rb:7:in `run'
```

**Comment by bperucchi** [comment]
I have the same problem but it's very strange because the implementation worked the first few times

```ruby
Mailman.config.pop3 = {
  :username => 'xxx@gmail.com',
  :password => 'xxx',
  :server   => 'pop.gmail.com',
  :port     => 995, # you can usually omit this, but it's there
  :ssl      => true # defaults to false
}

Mailman::Application.run do
  default do
    Nfe.incoming_mail(message)
  end
end
```


```
[2015-05-21T01:21:03.703457 #24344] ERROR -- : Error encountered processing message: #<Net::POPMail 45>
 EOFError: end of file reached
 /home/app/.rbenv/versions/2.2.0/lib/ruby/2.2.0/openssl/buffering.rb:182:in `sysread_nonblock'
/home/app/.rbenv/versions/2.2.0/lib/ruby/2.2.0/openssl/buffering.rb:182:in `read_nonblock'
```

**Comment by divyaiyer** [comment]
Any solution for this issue? I have added a daemon to read emails using IMAP..but daemon gets killed every now and then with same error en of the file reached , retrying..

Please let me know..

**Comment by KieranP** [comment]
@divyaiyer This is what we ended up using:

```
  Daemons.run_proc("mailman_server", :dir => pid_dir, :dir_mode => :normal) do
    begin
      Mailman.config.logger = Logger.new(Rails.root.join("log/mailman.log"))
      Mailman.config.pop3 = APP_CONFIG[:mailman_accounts_auth_settings]
      Mailman.config.poll_interval = 60
      Mailman.config.ignore_stdin = true

      Mailman::Application.run do
        to(/^..................$/) do |identifier|
          ActiveRecord::Base.verify_active_connections!
          # Other code here
        end
      end
    rescue Net::POPAuthenticationError
      retry # Error is temporary - simply keep retrying it
    rescue IOError
      retry # Connection already closed, so ignore and retry
    rescue => exception
      # The Mailman process has thrown an error and stopped.
      Rollbar.error(exception) # Report it
      retry                    # Restart it
    end
  end
```

**Comment by divyaiyer** [comment]
Thanks @KieranP , I shall try and post my findings here.

**Comment by bperucchi** [comment]
nice @KieranP.

**Comment by divyaiyer** [comment]
Still getting same issue with above setting :( 

end of file reached
Retrying...
end of file reached
Retrying...

**Comment by divyaiyer** [comment]
Runs fine for 3-4 hours and then this happens :( 
We are using it for an application which has to be up for 24/7

**Comment by divyaiyer** [comment]
As of now, I wrote a script and running a cron to start if it gets stopped.
